### ISSUE TITLE
Install hiccup in Julia 1.8.2

### ISSUE THREAD

**Issue by MooersLab** [ericsfraga/NatureInspiredOptimization.jl#1]
Hi Eric,

I upgraded Julia to 1.8.2 and then ran `] add https://github.com/ericsfraga/NatureInspiredOptimization.jl.git

```julia
(@v1.8) pkg> add Jacaranda
ERROR: The following package names could not be resolved:
 * Jacaranda (not found in project, manifest or registry)
   Suggestions: MLJParticleSwarmOptimization
```

So  I then ran

```julia
add https://gitlab.com/ericsfraga/Jacaranda.jl
add https://github.com/ericsfraga/NatureInspiredOptimization.jl.git
 37 dependencies successfully precompiled in 116 seconds.
```
The installation seems to be good now.

**Comment by ericsfraga** [comment]
Thank you for highlighting this. I will make it clear in the book that the Jacaranda Julia package is not registered in the Julia ecosphere! It's a very specific package but if there appears to be interest, I will try to get it registered.
Also thank you for trying this out with 1.8 as I have not yet upgraded my own Julia installation.
I will leave the issue open for now just to remind myself of the need to update the book.

**Comment by ericsfraga** [comment]
I removed the dependency of the NatureInspiredOptimization package on Jacaranda as Jacaranda is only required for the specific chlorobenzene case study and not the actual optimization codes.
